# -*- coding: utf-8 -*-
"""Exercise_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gj3GYvEcRivdckuNPBGN8dC00h6H2YuD
"""

def dijkstra(graph,src,dest,visited=[],distances={},predecessors={}):
    """ calculates a shortest path tree routed in src
    """    
    # a few sanity checks
    if src not in graph:
        raise TypeError('The root of the shortest path tree cannot be found')
    if dest not in graph:
        raise TypeError('The target of the shortest path cannot be found')    
    # ending condition
    if src == dest:
        # We build the shortest path and display it
        path=[]
        pred=dest
        while pred != None:
            path.append(pred)
            pred=predecessors.get(pred,None)
        print('shortest path: '+str(path)+" cost="+str(distances[dest])) 
    else :     
        # if it is the initial  run, initializes the cost
        if not visited: 
            distances[src]=0
        # visit the neighbors
        for neighbor in graph[src] :
            if neighbor not in visited:
                new_distance = distances[src] + graph[src][neighbor]
                if new_distance < distances.get(neighbor,float('inf')):
                    distances[neighbor] = new_distance
                    predecessors[neighbor] = src
        # mark as visited
        visited.append(src)
        # now that all neighbors have been visited: recurse                         
        # select the non visited node with lowest distance 'x'
        # run Dijskstra with src='x'
        unvisited={}
        for k in graph:
            if k not in visited:
                unvisited[k] = distances.get(k,float('inf'))        
        x=min(unvisited, key=unvisited.get)
        dijkstra(graph,x,dest,visited,distances,predecessors)
        


if __name__ == "__main__":
    #import sys;sys.argv = ['', 'Test.testName']
    #unittest.main()
    # graph = {'s': {'a': 2, 'b': 1},
    #         'a': {'s': 3, 'b': 4, 'c':8},
    #         'b': {'s': 4, 'a': 2, 'd': 2},     # Modify this section of the code for the graph given in the exercise sheet
    #         'c': {'a': 2, 'd': 7, 't': 4},     # Pick different sources and destinations and run the code
    #         'd': {'b': 1, 'c': 11, 't': 5},
    #         't': {'c': 3, 'd': 5}}
    


#     graph = {
#     'a': {'f': 14, 'b': 7, 'c': 9},
#     'f': {'a': 14, 'e': 9, 'c': 2},
#     'e': {'f': 9, 'd': 6},
#     'd': {'e': 6, 'b': 15, 'c': 11},
#     'b': {'d': 15, 'a': 7, 'c': 10},
#     'c': {'a': 9, 'f': 2, 'd': 11, 'b': 10}
# }

    graph = {
    1: {2: 50, 4: 10, 3: 45},
    2: {3: 10, 4: 15},
    3: {5: 30},
    4: {1: 10, 5: 15},
    5: {3: 35},
    6: {5:1}
}

  

    dijkstra(graph, 4,3)

